import Head from "next/head";
import Image from "next/image";

import styles from "../styles/Home.module.css";

export default function About() {
  return (
    <div className={styles.container}>
      <Head>
        <title>TOINApp-About</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    <h1 className="center"> ABOUT US </h1>
    <h3 className="center"> TION App : The Internets Own News App </h3>
    
    <div className="card-panel center">
    <h5 className="blue-text text-darken-5 font-style"><i> TION App is a WEB3 News Network providing the News which you can trust!</i></h5>
    </div>
        
  <div className="divider"></div>
  <div className="section center">
    <h5 className="center"> <b>The issue with current News System :</b></h5>
    <div className="center">
    <div className="row center">
    <div className="col s10 offset-s1">
      <div className="card-panel #263238 blue-grey darken-4 center">
        <span className="white-text center font-style">It is pretty obvious that corporate Media is dying. Not many people watch or trust the mainstream media which is showcased on TV or other news platforms.  But these big media companies can still force feed us a specified news content by making it artificially ranked high on news and social media platforms. Further they can also instill means which will make it hard for the normal public to report bad content. 
        </span>
      </div>
    </div>
  </div>
  </div>
  </div>
  <div className="divider"></div>
  <div className="section">
    <h5 className="center"><b>So to tackle this issue : </b> </h5>
    <div className="row">
    <div className="col s10 offset-s1">
      <div className="card-panel #263238 blue-grey darken-4">
        <span className="white-text font-style">We thought of creating an entirely decentralized news system network, where journalists can upload news content like articles, photos and videos. This incentivises good journalism and eliminates the possibility of a top-down propaganda machine. 
        </span>
      </div>
    </div>
  </div>
  </div>
  <div className="row">
      <div className="grid-example col s12 center"><span className="flow-text thin">Hence, Journalism Wins! Consumer Wins!  </span></div>
    </div>
    <style jsx>
        {`
        .font-style{
          font-family: Calibri;
          font-size:22px;
        }
        `}
      </style>
    </div>
  );
}
